port: 10809       # HTTP inbound
socks-port: 10808 # SOCKS inbound
allow-lan: false
mode: Rule
log-level: silent
ipv6: true

dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 172.67.73.38
    - 104.19.155.92
    - 172.67.73.163
    - 104.18.155.42
    - 104.16.124.175
    - 104.16.248.249
    - 104.16.249.249
    - 104.26.13.8
    - 1.1.1.1
    - 8.8.8.8
  fallback:
    - 1.1.1.1
    - 8.8.8.8
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/0
    domain: true

proxies:
  - name: fragment-out
    type: direct
  - name: fakeproxy-out
    type: vmess
    server: google.com
    port: 443
    uuid: "UUID"
    alterId: 0
    cipher: auto
    network: ws
    ws-path: "/"
    ws-headers:
      Host: google.com
    tls: true
    skip-cert-verify: false
  - name: dns-out
    type: direct

proxy-groups:
  - name: NOPROXY
    type: select
    proxies:
      - DIRECT

  - name: BLOCK
    type: select
    proxies:
      - REJECT

rules:
  # DNS traffic goes to dns-out
  - DOMAIN-SUFFIX,google.com,dns-out
  - MATCH,fragment-out
