mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  nameserver:
    - https://cloudflare-dns.com/dns-query
  hosts:
    cloudflare-dns.com:
      - 172.67.73.38
      - 104.19.155.92
      - 172.67.73.163
      - 104.18.155.42
      - 104.16.124.175
      - 104.16.248.249
      - 104.16.249.249
      - 104.26.13.8
    youtube.com: google.com

proxies:
  - name: fakeproxy-out
    type: vless
    server: google.com
    port: 443
    uuid: UUID
    udp: true
    tls: true
    servername: google.com
    fingerprint: randomized
    alpn:
      - h2
      - http/1.1
    network: ws
    ws-opts:
      path: /
      headers:
        Host: google.com

  - name: fragment-out
    type: direct
    udp: true
    # ⚠ NOTE: Clash/FlClash does not support Xray's "fragment" feature
    # Original settings: interval=5-10, length=1-3, packets=1-1

  - name: dns-out
    type: dns

proxy-groups:
  - name: Default
    type: select
    proxies:
      - fakeproxy-out
      - fragment-out
      - DIRECT

rules:
  # Route DNS queries to dns-out
  - DST-PORT,53,dns-out

  # All other traffic to fragment-out
  - DST-PORT,0-65535,fragment-out

  # Final fallback
  - MATCH,Default
